
tests := \
	mvin_mvout \
	mvin_mvout_stride \
	mvin_mvout_acc \
	mvin_mvout_acc_stride \
	matmul_os \
	matmul_ws \
	matmul \
	raw_hazard \
	aligned \
	padded \
	mvin_scale \
	conv \
	conv_with_pool \
	tiled_matmul_os \
	tiled_matmul_ws \
	tiled_matmul_cpu \
	tiled_matmul_option \
	transpose \
	template \
	gemm

