include $(abs_top_srcdir)/Makefrag

tests = \
	planaria_mp8 \
	planaria_mp8_h \
	planaria_mp8_l \
	priority_mp8_staticb \
	priority_mp8_staticb3 \
	priority_mp8_staticb2 \
	priority_mp8_static \
	priority_mp8_static1 \
	priority_mp8_static2 \
	priority_mp8_dynamicb \
	priority_mp8_dynamicb_l \
	priority_mp8_dynamicb_h \
	prema_mp8 \
	prema_mp8_l \
	prema_mp8_h \
	resnet_batch1_4 \
	alexnet_batch1_4 \
	googlenet_batch1_4 \
	squeezenet_batch1_4 \
	resnet_batch1_2 \
	alexnet_batch1_2 \
	googlenet_batch1_2 \
	squeezenet_batch1_2 \
	motivation_4 \
	motivation_3 \
	motivation_2 \
	motivation_1 \
	#priority_mp_dynamic3_mod2_batch8 \
	#priority_mp_dynamic2_mod2_batch8 \
	#priority_mp_static2_mod2_batch8 \
	#priority_mp_static2_mod1_batch8 \
	#priority_mp_dynamic3_mod1_batch8 \
	#priority_mp_dynamic2_mod1_batch8 \
	#fcfs_mp_mod2_batch8 \
	#fcfs_sp_mod2_batch8 \
	#fcfs_mp_mod1_batch8 \
	#fcfs_sp_mod1_batch8 \
	#yolonet_batch8_8 \
	#kwsnet_batch8_8 \
	#fcnnet_batch8_8 \
	#resnet_batch8_8 \
	#alexnet_batch8_8 \
	#googlenet_batch8_8 \
	#yololitenet_batch8_8 \
	#squeezenet_batch8_8 \
	#yolonet_batch4_8 \
	#kwsnet_batch4_8 \
	#fcnnet_batch4_8 \
	#resnet_batch4_8 \
	#alexnet_batch4_8 \
	#googlenet_batch4_8 \
	#yololitenet_batch4_8 \
	#squeezenet_batch4_8 \
	#yolonet_batch2_8 \
	#kwsnet_batch2_8 \
	#fcnnet_batch2_8 \
	#resnet_batch2_8 \
	#alexnet_batch2_8 \
	#googlenet_batch2_8 \
	#yololitenet_batch2_8 \
	#squeezenet_batch2_8 \
	#yolonet_batch1_8 \
	#kwsnet_batch1_8 \
	#fcnnet_batch1_8 \
	#resnet_batch1_8 \
	#alexnet_batch1_8 \
	#googlenet_batch1_8 \
	#yololitenet_batch1_8 \
	#squeezenet_batch1_8 \
	#yolonet_batch8_4 \
	#yolonet_batch1_4 \
	#kwsnet_batch1_4 \
	#fcnnet_batch1_4 \
	#resnet_batch1_4 \
	#alexnet_batch1_4 \
	#googlenet_batch1_4 \
	#yololitenet_batch1_4 \
	#squeezenet_batch1_4 \
	#kwsnet_batch1_2 \
	#yolonet_batch1_2 \
	#yololitenet_batch1_2 \
	#fcnnet_batch1_2 \
	#resnet_batch1_2 \
	#alexnet_batch1_2 \
	#googlenet_batch1_2 \
	#squeezenet_batch1_2 \
	#kwsnet_batch1_1 \
	#yolonet_batch1_1 \
	#yololitenet_batch1_1 \
	#fcnnet_batch1_1 \
	#resnet_batch1_1 \
	#alexnet_batch1_1 \
	#googlenet_batch1_1 \
	#squeezenet_batch1_1 \
	#kwsnet_batch2_4 \
	#yolonet_batch2_4 \
	#yololitenet_batch2_4 \
	#fcnnet_batch2_4 \
	#resnet_batch2_4 \
	#alexnet_batch2_4 \
	#googlenet_batch2_4 \
	#squeezenet_batch2_4 \
	#kwsnet_batch2_2 \
	#yolonet_batch2_2 \
	#yololitenet_batch2_2 \
	#fcnnet_batch2_2 \
	#resnet_batch2_2 \
	#alexnet_batch2_2 \
	#googlenet_batch2_2 \
	#squeezenet_batch2_2 \
	#kwsnet_batch2_1 \
	#yolonet_batch2_1 \
	#yololitenet_batch2_1 \
	#fcnnet_batch2_1 \
	#resnet_batch2_1 \
	#alexnet_batch2_1 \
	#googlenet_batch2_1 \
	#squeezenet_batch2_1 \
	#kwsnet_batch8_4 \
	#fcnnet_batch8_4 \
	#resnet_batch8_4 \
	#alexnet_batch8_4 \
	#googlenet_batch8_4 \
	#yololitenet_batch8_4 \
	#squeezenet_batch8_4 \
	#kwsnet_batch8_2 \
	#yolonet_batch8_2 \
	#yololitenet_batch8_2 \
	#fcnnet_batch8_2 \
	#resnet_batch8_2 \
	#alexnet_batch8_2 \
	#googlenet_batch8_2 \
	#squeezenet_batch8_2 \
	#kwsnet_batch8_1 \
	#yolonet_batch8_1 \
	#yololitenet_batch8_1 \
	#fcnnet_batch8_1 \
	#resnet_batch8_1 \
	#alexnet_batch8_1 \
	#googlenet_batch8_1 \
	#squeezenet_batch8_1 \
	#kwsnet_batch4_4 \
	#yolonet_batch4_4 \
	#yololitenet_batch4_4 \
	#fcnnet_batch4_4 \
	#resnet_batch4_4 \
	#alexnet_batch4_4 \
	#googlenet_batch4_4 \
	#squeezenet_batch4_4 \
	#kwsnet_batch4_2 \
	#yolonet_batch4_2 \
	#yololitenet_batch4_2 \
	#fcnnet_batch4_2 \
	#resnet_batch4_2 \
	#alexnet_batch4_2 \
	#googlenet_batch4_2 \
	#squeezenet_batch4_2 \
	#kwsnet_batch4_1 \
	#yolonet_batch4_1 \
	#yololitenet_batch4_1 \
	#fcnnet_batch4_1 \
	#resnet_batch4_1 \
	#alexnet_batch4_1 \
	#googlenet_batch4_1 \
	#squeezenet_batch4_1 \
	#fcfs_mp_mod1 \
	#fcfs_mp_mod2\
	#fcfs_sp_mod1 \
	#fcfs_sp_mod2 \
	#googlenet_batch8_re \
	#priority_mp_dynamic3_mod2_batch4 \
	#priority_mp_dynamic2_mod2_batch4 \
	#priority_mp_static2_mod2_batch4 \
	#priority_mp_static2_mod1_batch4 \
	#priority_mp_dynamic3_mod1_batch4 \
	#priority_mp_dynamic2_mod1_batch4 \
	#priority_mp_static2_mod1 \
	#priority_mp_static2_mod2 \
	#priority_mp_dynamic3_mod1 \
	#priority_mp_dynamic3_mod2 \
	#priority_mp_dynamic2_mod1 \
	#priority_mp_dynamic2_mod2 \
	#priority_mp_static_mod1 \
	#priority_mp_static_mod2 \

tests_baremetal = $(tests:=-baremetal)
runs_baremetal = $(addsuffix .run,$(tests_baremetal))
ifdef BAREMETAL_ONLY
	tests_linux =
else
	tests_linux = $(tests:=-linux)
endif

BENCH_COMMON = $(abs_top_srcdir)/riscv-tests/benchmarks/common
GEMMINI_HEADERS = $(abs_top_srcdir)/include/gemmini.h $(abs_top_srcdir)/include/gemmini_params.h $(abs_top_srcdir)/include/gemmini_nn.h $(abs_top_srcdir)/include/gemmini_testutils.h

CFLAGS := $(CFLAGS) \
	-DPREALLOCATE=1 \
	-DMULTITHREAD=1 \
	-mcmodel=medany \
	-std=gnu99 \
	-O2 \
	-ffast-math \
	-fno-common \
	-fno-builtin-printf \
	-march=rv64gc -Wa,-march=rv64gcxhwacha \
	-lm \
	-lgcc \
	-lpthread \
	-I$(abs_top_srcdir)/riscv-tests \
	-I$(abs_top_srcdir)/riscv-tests/env \
	-I$(abs_top_srcdir) \
	-I$(BENCH_COMMON) \
	-DID_STRING=$(ID_STRING) \
	-Wno-incompatible-pointer-types

CFLAGS_BAREMETAL := \
	$(CFLAGS) \
	-nostdlib \
	-nostartfiles \
	-static \
	-T $(BENCH_COMMON)/test.ld \
	-DBAREMETAL=1 \

all: $(tests_linux)

vpath %.c $(src_dir)

%-baremetal: %.c $(src_dir)/images.h $(GEMMINI_HEADERS)
	$(CC_BAREMETAL) $(CFLAGS_BAREMETAL) $< $(LFLAGS) -o $@ \
		$(wildcard $(BENCH_COMMON)/*.c) $(wildcard $(BENCH_COMMON)/*.S) $(LIBS)

%-linux: %.c $(src_dir)/images.h $(GEMMINI_HEADERS)
	$(CC_LINUX) $(CFLAGS) $< $(LFLAGS) -o $@

run-baremetal: $(runs_baremetal)

%-baremetal.run: %-baremetal
	$(RUNNER)$^

junk += $(tests_baremetal) $(tests_linux)

